### ISSUE TITLE
Customize the layout

### ISSUE THREAD

**Issue by Verdurakh** [maoni-app/maoni#58]
Any way to change the current layout?

I would like to get rid of the title and image and maybe change the position of the send button.
Is there any support for that or any planned feature?

**Comment by ddinchev** [comment]
You could do a `.addUiListener()` of `Maoni.Builder` - the callback receives the root `View` element and from there you can find and hide/change the internal views.

**Comment by rm3l** [comment]
As mentioned above, the root `View` is utterly accessible for customization.
